<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>pl.homeportal</groupId>
        <artifactId>homeportal-commons</artifactId>
        <version>6.0</version>
    </parent>

    <artifactId>homeportal-commons-mail</artifactId>

    <dependencies>

        <!-- INTERNALS -->
        <dependency>
            <groupId>pl.homeportal</groupId>
            <artifactId>homeportal-commons-java</artifactId>
            <version>${project.parent.version}</version>
        </dependency>

        <dependency>
            <groupId>pl.homeportal</groupId>
            <artifactId>homeportal-commons-logging</artifactId>
            <version>${project.parent.version}</version>
        </dependency>

        <!-- EXTERNALS -->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>

        <dependency>
            <groupId>com.sun.mail</groupId>
            <artifactId>javax.mail</artifactId>
        </dependency>

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-email</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.apache.velocity</groupId>
            <artifactId>velocity</artifactId>
            <scope>provided</scope>
        </dependency>

        <!-- TESTS -->
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>

    </dependencies>
</project>
